const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const context={window:{}};vm.createContext(context);for(const f of ['model','bonding','geometry','io','molfile','history'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f+'.js'),'utf8'),context);
const {IO,Model:M,Geometry:G,Bonding:B,History}=context.window.MoleculeVisualizer;
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
test('XYZ preserves blank comment, all atoms, exponent notation and rejects partial data',()=>{const s=IO.parseXYZToState('3\n\nO 0 0 0\nH 9.572D-1 0 0\nH -.239987 .926627 0\n');assert.equal(s.atoms.length,3);near(s.atoms[1].x,.9572);assert.equal(IO.parseXYZToState(IO.stateToXYZText(s)).atoms.length,3);for(const t of ['2\nwater\nH 0 0 0','H 0 a 0','Xx 0 0 0','TV 1 0 0','H 0 0 0 extra','1\n\nH 0 0 0\n1\n\nH 1 0 0'])assert.throws(()=>IO.parseXYZToState(t));});
test('MOL and SDF round trip preserves charge and aromatic bonds',()=>{const s=IO.parseXYZToState('C 0 0 0\nN 1.4 0 0');s.atoms[1].charge=1;s.bonds[0].order=4;s.bonds[0].source='manual';s.metadata.sdfProperties='> <ID>\nsample-1';const t=IO.stateToSDFText(s),r=IO.parseMolToState(t);assert.match(IO.stateToSDFText(r),/sample-1/);assert.equal(r.atoms[1].charge,1);assert.equal(r.bonds[0].order,4);assert.throws(()=>IO.parseMolToState(t.replace('V2000','V3000')));assert.throws(()=>IO.parseMolToState(t+t));s.bonds[0].type='hydrogen';assert.throws(()=>IO.stateToMolText(s,"V2000"));assert.equal(IO.parseMolToState(IO.stateToMolText(s)).bonds[0].type,"hydrogen");const j=IO.parseProject(IO.stateToProjectText(s));assert.equal(j.bonds[0].type,'hydrogen');assert.equal(j.atoms[1].charge,1);});
test('distance, angle and signed dihedral edits reach their targets',()=>{const a={x:1,y:0,z:0},b={x:0,y:0,z:0},c={x:0,y:1,z:0},d={x:1,y:1,z:1};near(G.distance(a,G.setDistance(a,b,2)),2);for(const target of [0,45,109.5,180])near(G.angle(a,b,G.setAngle(a,b,c,target)),target);for(const target of [-170,-90,0,60,179])near(G.dihedral(a,b,c,G.setDihedral(a,b,c,d,target)),target);near(G.angle(a,b,G.setAngle(a,b,{x:-1,y:0,z:0},90)),90);assert.throws(()=>G.dihedral(a,b,{x:-1,y:0,z:0},d));});
test('undo/redo restores coordinates and deleted bonds stay deleted after coordinate edits',()=>{const s=IO.parseXYZToState('C 0 0 0\nH 1.1 0 0'),h=new History();h.push('before',s);s.atoms[1].x=2;const prior=h.undo(s);near(prior.atoms[1].x,1.1);near(h.redo(prior).atoms[1].x,2);s.atoms[1].x=1.1;M.setSelectedBonds(s,[s.bonds[0].id]);M.removeSelectedBonds(s);B.refreshInferredBonds(s);assert.equal(s.bonds.length,0);const saved=IO.parseProject(IO.stateToProjectText(s));B.refreshInferredBonds(saved);assert.equal(saved.bonds.length,0);});
test('MOL V2000 retains isotope, radical, atom parity, mapping and wedge through undo and V3000',()=>{
 const s=IO.parseXYZToState('C 0 0 0\nO 1.4 0 0');s.atoms[0].mol={props:{MASS:'13',RAD:'2',CFG:'1',VAL:'3'},map:42};s.atoms[0].charge=1;s.bonds[0].source='manual';s.bonds[0].mol={props:{CFG:'3'}};s.metadata.chiralFlag=1;
 const mol=IO.stateToMolText(s,'V2000'),parsed=IO.parseMolToState(mol);assert.equal(parsed.atoms[0].mol.props.MASS,'13');assert.equal(parsed.atoms[0].mol.props.RAD,'2');assert.equal(parsed.atoms[0].mol.props.CFG,'1');assert.equal(parsed.atoms[0].mol.map,42);assert.equal(parsed.atoms[0].charge,1);assert.equal(parsed.bonds[0].mol.props.CFG,'3');
 const h=new History();h.push('chemical attributes',parsed);parsed.atoms[0].x=3;const prior=h.undo(parsed);assert.equal(prior.atoms[0].mol.props.MASS,'13');const copy=IO.parseMolToState(IO.stateToMolV3000Text(prior));assert.equal(copy.atoms[0].mol.props.RAD,'2');assert.equal(copy.atoms[0].mol.map,42);assert.equal(copy.bonds[0].mol.props.CFG,'3');
 // Legacy mass-difference and inline doublet radical, without M ISO/RAD.
 const l=IO.stateToMolText(s,'V2000').split('\n').filter(x=>!/^M  (ISO|RAD|CHG)/.test(x));l[4]=l[4].slice(0,34)+' 1  4'+l[4].slice(39);const legacy=IO.parseMolToState(l.join('\n'));assert.equal(legacy.atoms[0].mol.props.MASS,'13');assert.equal(legacy.atoms[0].mol.props.RAD,'2');
});
test('V3000 nonsequential IDs, continuation, stereogroups and chemical properties survive coordinate edits',()=>{
 const text='attributes\n\n\n  0  0  0  0  0  0            999 V3000\nM  V30 BEGIN CTAB\nM  V30 COUNTS 2 1 0 0 1\nM  V30 BEGIN ATOM\nM  V30 10 C 1.25 2 3 17 MASS=13 RAD=2 -\nM  V30 CFG=1 CHG=-1\nM  V30 30 O 2.5 2 3 0\nM  V30 END ATOM\nM  V30 BEGIN BOND\nM  V30 7 1 10 30 CFG=1\nM  V30 END BOND\nM  V30 BEGIN COLLECTION\nM  V30 MDLV30/STEABS ATOMS=(1 10)\nM  V30 END COLLECTION\nM  V30 END CTAB\nM  END\n';
 const s=IO.parseMolToState(text);s.atoms[0].x=9;const restored=IO.parseProject(IO.stateToProjectText(M.cloneState(s))),r=IO.parseMolToState(IO.stateToMolV3000Text(restored));assert.equal(r.atoms[0].x,9);assert.equal(r.atoms[0].mol.props.MASS,'13');assert.equal(r.atoms[0].mol.props.RAD,'2');assert.equal(r.atoms[0].mol.props.CFG,'1');assert.equal(r.atoms[0].mol.map,17);assert.equal(r.atoms[0].charge,-1);assert.equal(r.metadata.stereoGroups[0].atomIds[0],r.atoms[0].id);assert.equal(r.bonds[0].mol.props.CFG,'1');
 for(const bad of [text.replace('COUNTS 2 1','COUNTS 3 1'),text.replace('1 10 30','1 10 99'),text.replace('30 O','10 O'),text.replace('RAD=2','RAD=8'),text.replace('END CTAB','END WRONG')])assert.throws(()=>IO.parseMolToState(bad));
});
